In [ ]:
#@title [Candidature form]

Name = '' #@param {type: "string"}
Matriculation_number = '' #@param {type:"string"}
Faculty = ''  #@param {type: "string"}
Course = '' #@param {type:"string"}
Current_semester = "" #@param ["1", "2", "3", "4", "5", "6", "7"] {allow-input: true}

Python_skills = 5 #@param {type:"slider", min:1, max:5, step:1}

# **Python Tutorial with Google Colab**

This tutorial is created and adapted as a Jupyter notebook for [**MME 26849: "Fundamentals of Deep Learning and TinyML"**](https://felix.hs-furtwangen.de/url/RepositoryEntry/4020862983) by the course instructors [Marcus Rüb](https://linkedin.com/in/marcus-rüb-3b07071b2) and [Ajay Krishna](https://linkedin.com/in/ajay-krishna-2031a5119).

In this Jupyter Notebook titled "*Python Tutorial with Google Colab*" , we will cover:
* **Basic Python:** Data types (Numbers, Booleans, Strings), Containers (Loops, Lists, Dictionaries, Sets, Tuples), Functions, and Classes.
* **NumPy:** Arrays, Array indexing, Data types, Array math, and Broadcasting.
* **Pandas:** Data frames, Data visualization, and Data cleaning (Empty cells, Wrong format, Wrong data, Duplicates).
* **Matplotlib:** Plotting, Subplots, Images, Contouring and Pseudocolor, Histograms, and Scatter plots.

This notebook also contains questionnaires under each topic/sub-topic that have to be answered. You would probably require to go through the following resources ***(only those who are new to programming)*** to answer some of the questions and understand the complete concept behind it.

***Resources for answering questions:***
1. [Basic Python](https://docs.python.org/3/tutorial/)  
2. [NumPy](https://numpy.org/doc/stable/user/basics.html) 
3. [Pandas](https://pandas.pydata.org/docs/user_guide/10min.html) 
4. [Matplotlib](https://matplotlib.org/stable/tutorials/index.html)


```
P.S. Goodluck and we hope to see you all as potential future Data Scientists and ML Engineers!
```







## **Introduction** 

Python is a high-level object-oriented programming language which has built-in data structures, combined with dynamic binding and typing, which makes it an ideal choice for rapid application development. 

It also offers support for modules and packages, which allows system modularity and code reuse. It is one of the fastest programming languages as it requires very few lines of code. Its emphasis is mainly on readability and simplicity, which makes it a great choice for beginners and a powerful environment for scientific computing with the help of a few popular libraries such as NumPy, Pandas, SciPy, Scikit-learn, Matplotlib etc.


This notebook will serve as a quick crash course on the Python programming language itself and on the use of Python for scientific computing.









## **Brief Note on Python Versions**

As of Janurary 1, 2020, Python has [officially dropped support](https://www.python.org/doc/sunset-python-2/) for `python2`. We'll be using Python 3.7.10 for this iteration of the course. You can check your Python version at the command line by running `python --version`.  

Note that as of April 2020, Colab uses Python 3.6.9 which should run everything without any errors.

In [ ]:
!python --version

## **Brief Note on Computational Power**

* All the students who have better GPUs than Nvidia K80s, T4s, P4s and P100s can run the Colab code with your own hardware and [here](https://research.google.com/colaboratory/local-runtimes.html) is the way to set that up.

* Rest of the students can use Colab's computational resources for free and can enforce by clicking `Runtime -> Change Runtime Type -> Hardware Accelerator -> GPU`

## **1. Basic Python: Data types, Containers (Lists, Dictionaries, Sets, Tuples), Functions, Classes**

Before deep diving, let's start off with the most common program of all time as a tradition! ;)

In [ ]:
print("Hello World!")

### **Data Types**

In [ ]:
x = "Cyberpunk"
y = 2077
z = 3.142957

print(x, type(x))   # prints data type of x
print(y, type(y))   # prints data type of y
print(z, type(z))   # prints data type of z

In [ ]:
#@title Questionnaire: 
#@markdown 1. What is data type of?
#@markdown  - "Hello"
Ans = "" #@param ["Float", "String", "Integer", "Boolean"] {allow-input: true}



#### **Numbers**

Integers and floats work as you would expect from other languages:

In [ ]:
x = 3

print(x, type(x)) # prints data type of x

In [ ]:
print(x + 1)      # addition
print(x - 1)      # subtraction
print(x * 2)      # multiplication
print(x ** 2)     # exponentiation

In [ ]:
x += 1
print(x)

x *= 2
print(x)

In [ ]:
y = 2.5

print(type(y))                  # prints data type of y
print(y, y + 1, y * 2, y ** 2)  # prints various mathematical operations

**Note:**

Unlike many languages, Python does not have unary increment (x++) or decrement (x--) operators.

Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#numeric-types-int-float-long-complex).

In [ ]:
#@title Questionnaire: 
#@markdown 2. What is output of? 
#@markdown  - z = 3.5
#@markdown  - print(z ** 3)
Ans = "" #@param {type:"string"}



In [ ]:
# You can run the above code here to obtain the answer

z =
print()

#### **Booleans**

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):

In [ ]:
t, f = True, False

print(type(t))

Now, let's look at the operations

In [ ]:
print(t and f) # logical AND;
print(t or f)  # logical OR;
print(not t)   # logical NOT;
print(t != f)  # logical XOR;

In [ ]:
#@title Questionnaire: 
#@markdown 3. This operator means that one value is not equal to another value? 
#@markdown - A) ==
#@markdown - B) <=
#@markdown - C) !=
#@markdown - D) >=
Ans = "" #@param ["A", "B", "C", "D"] {allow-input: true}

#### **Strings**

In [ ]:
a = 'hello'       # string literals can use single quotes
b = "world"       # or double quotes; it does not matter

print(a)
print(b)
print(len(b))     # length of the string

In [ ]:
hw = "hello" + ' ' + "world"           # string concatenation

print(hw)

In [ ]:
hw12 = '{} {} {}'.format(a, b, 12)  # string formatting

print(hw12)

String objects have a bunch of useful methods; for example:

In [ ]:
s = "hello"

print(s.capitalize())           # capitalize a string
print(s.upper())                # convert a string to uppercase; prints "HELLO"
print(s.rjust(7))               # right-justify a string, padding with spaces
print(s.center(7))              # center a string, padding with spaces
print(s.replace('l', '(ell)'))  # replace all instances of one substring with another
print('  world '.strip())       # strip leading and trailing whitespace

You can find a list of all string methods in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#string-methods).

In [ ]:
#@title Questionnaire: 
#@markdown 4. What is the output of the following code? 
#@markdown  - *str1 = "PYnative"*
#@markdown  - *print(str1[1:4], str1[:5], str1[4:], str1[0:-1], str1[:-1])*

#@markdown - A) PYn PYnat ive PYnativ vitanYP
#@markdown - B) Yna PYnat tive PYnativ vitanYP
#@markdown - C) Yna PYnat tive PYnativ PYnativ
Ans = "" #@param ["A", "B", "C"] {allow-input: true}

### **Containers**

Python includes several built-in container types: lists, dictionaries, sets, and tuples.

In [ ]:
xs = [3, 1, 2]      # create a list

print(xs, xs[2])
print(xs[-1])       # negative indices count from the end of the list; prints "2"

In [ ]:
xs[2] = 'foo'       # lists can contain elements of different types

print(xs)

In [ ]:
xs.append('bar')    # add a new element to the end of the list

print(xs)  

As usual, you can find all the glory details about lists in the [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#more-on-lists).

#### **Slicing**

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [ ]:
nums = list(range(5)) # range is a built-in function that creates a list of integers
print(nums)           # prints "[0, 1, 2, 3, 4]"
print(nums[2:4])      # get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])       # get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])       # get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])        # get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])      # slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9]    # assign a new sublist to a slice
print(nums)           # prints "[0, 1, 8, 9, 4]"

#### **Loops**

You can loop over the elements of a list like this:

In [ ]:
animals = ['cat', 'dog', 'monkey']

for animal in animals:
    print(animal)

If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [ ]:
animals = ['cat', 'dog', 'monkey']

for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

#### **List comprehensions**

While programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []

for x in nums:
    squares.append(x ** 2)
    
print(squares)

You can make this code simpler using a list comprehension:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]

print(squares)

List comprehensions can also contain conditions:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]

print(even_squares)

In [ ]:
#@title Questionnaire: 
#@markdown 5. What is the output of the following list operation?
#@markdown  - *list = [10, 20, 30, 40, 50, 60, 70, 80]*
#@markdown  - *print(list[2:5])*
#@markdown  - *print(list[:4])*
#@markdown  - *print(list[3:])*
#@markdown - A) [20, 30, 40, 50]
#@markdown [10, 20, 30, 40]
#@markdown [30, 40, 50, 60, 70, 80]
#@markdown - B) [30, 40, 50]
#@markdown [10, 20, 30, 40]
#@markdown [40, 50, 60, 70, 80]
Ans = "" #@param ["A", "B"] {allow-input: true}

#### **Dictionaries**

A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}   # create a new dictionary with some data

print(d['cat'])                       # get an entry from a dictionary; prints "cute"
print('cat' in d)                     # check if a dictionary has a given key; prints "True"

In [ ]:
d['fish'] = 'wet'     # set an entry in a dictionary
print(d['fish'])      # prints "wet"

In [ ]:
print(d['monkey'])    # KeyError: 'monkey' not a key of d

In [ ]:
print(d.get('monkey', 'N/A'))   # get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))     # get an element with a default; prints "wet"

In [ ]:
del d['fish']                   # remove an element from a dictionary
print(d.get('fish', 'N/A'))     # "fish" is no longer a key; prints "N/A"

You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/2/library/stdtypes.html#dict).

It is easy to iterate over the keys in a dictionary:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}

for animal, legs in d.items():
    print('A {} has {} legs'.format(animal, legs))

**Dictionary comprehensions:** These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}

print(even_num_to_square)

#### **Sets**

A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [ ]:
animals = {'cat', 'dog'}

print('cat' in animals)   # check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"


In [ ]:
animals.add('fish')       # add an element to a set
print('fish' in animals)
print(len(animals))       # number of elements in a set

In [ ]:
animals.add('cat')        # adding an element that is already in the set does nothing
print(len(animals))      

animals.remove('cat')     # remove an element from a set
print(len(animals))       

**_Loops_:** Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [ ]:
animals = {'cat', 'dog', 'fish'}

for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

**Set comprehensions:** Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [ ]:
from math import sqrt                     # importing dependencies 
print({int(sqrt(x)) for x in range(30)})

In [ ]:
#@title Questionnaire: 
#@markdown 6. Suppose we are given with two sets (S1 & S2) then what is the output of the code 
#@markdown  - S1 + S2
#@markdown - A) Adds the elements of both the sets
#@markdown - B) Removes the repeating elements and then adds both the sets
#@markdown - C) It is a wrong command
#@markdown - D) Output will be stored in S1
Ans = "" #@param ["A", "B", "C", "D"] {allow-input: true}

####**Tuples**

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [ ]:
d = {(x, x + 1): x for x in range(10)}    # create a dictionary with tuple keys
t = (5, 6)                                # create a tuple

print(type(t))
print(d[t])       
print(d[(1, 2)])

### **Functions**

Python functions are defined using the `def` keyword. For example:

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

We will often define functions to take optional keyword arguments, like this:

In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))

hello('Bob')
hello('Fred', loud=True)

In [ ]:
#@title Questionnaire: 
#@markdown 7. Select which is true for Python function
#@markdown - A) A Python function can return only a single value
#@markdown - B) A Python function can return multiple values
#@markdown - C) Python function doesn’t return anything unless and until you add a return statement
Ans = "" #@param ["A", "B", "C"] {allow-input: true}

### **Classes**

The syntax for defining classes in Python is straightforward:

In [ ]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name        # create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
          print('HELLO, {}'.format(self.name.upper()))
        else:
          print('Hello, {}!'.format(self.name))

g = Greeter('Fred')             # construct an instance of the Greeter class
g.greet()                       # call an instance method; prints "Hello, Fred"
g.greet(loud=True)              # call an instance method; prints "HELLO, FRED!"

## **2. NumPy**

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To use Numpy, we first need to install and import the `numpy` package:

In [ ]:
!pip install numpy
import numpy as np

### **Arrays**

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [ ]:
a = np.array([1, 2, 3])                     # create a rank 1 array
print(type(a))
print(a.shape)
print(a[0])
print(a[1])
print(a[2])                 

In [ ]:
a[0] = 5                                    # change an element of the array
print(a) 

In [ ]:
b = np.array([[1,2,3],[4,5,6]])             # create a rank 2 array
print(b)

In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,2))         # create an array of all zeros
print(a)

In [ ]:
b = np.ones((1,2))          # create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7)       # create a constant array
print(c)

In [ ]:
d = np.eye(2)               # create a 2x2 identity matrix
print(d)

In [ ]:
e = np.random.random((2,2)) # create an array filled with random values
print(e)

### **Array indexing**

Numpy offers several ways to index into arrays.

**Slicing:** Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

print(b)

A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [ ]:
# create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a)

Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [ ]:
row_r1 = a[1, :]    # rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # rank 2 view of the second row of a
row_r3 = a[[1], :]  # rank 2 view of the second row of a

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

In [ ]:
# we can make the same distinction when accessing columns of an array:

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

**Integer array indexing:** When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# an example of integer array indexing.
# the returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# the above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

In [ ]:
# when using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)

In [ ]:
# create an array of indices
b = np.array([0, 2, 0, 1])

# select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

In [ ]:
# mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)

**Boolean array indexing:** Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

In [ ]:
# we use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# we can do all of the above in a single concise statement:
print(a[a > 2])

For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

### **Data types**

Every NumPy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])                  # let numpy choose the datatype
y = np.array([1.0, 2.0])              # let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # force a particular datatype

print(x.dtype, y.dtype, z.dtype)

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### **Array math**

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

In [ ]:
# elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

**Note:**

 `*` is elementwise multiplication, not matrix multiplication. 
 
 We instead use the `.` dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices.

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [ ]:
print(v @ w)

In [ ]:
# matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
# matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))          # compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # compute sum of each row; prints "[3 7]"

You can find the full list of mathematical functions provided by NumPy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n", x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

### **Broadcasting**

Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# we will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # create an empty matrix with the same shape as x

# add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [ ]:
vv = np.tile(v, (4, 1))  # stack 4 copies of v on top of each other

print(vv)                # prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
y = x + vv  # add x and vv elementwise
print(y)

NumPy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v                 # Add v to each row of x using broadcasting

print(y)

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [ ]:
# compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

# to compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

In [ ]:
# add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])

# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

In [ ]:
# add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# if we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

In [ ]:
# another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.

print(x + np.reshape(w, (2, 1)))

In [ ]:
# multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:

print(x * 2)

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about NumPy, but is far from complete. Check out the [NumPy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about it.

In [ ]:
#@title Questionnaire: 
#@markdown 8. Select the correct output from the below options
#@markdown  - *names = np.array(["Simon" , "Adrian" , "Klemens" , "Oli" , "Marcus"])*
#@markdown  - *print(names([2,3,4]))*

#@markdown - A) [ 'Klemens' 'Oli' 'Marcus' ]
#@markdown - B) [ 'Oli' 'Klemens' 'Marcus' ]
#@markdown - C) [ 'Simon' 'Adrian' 'Fatema' ]
#@markdown - D) [ 'Adrian' 'Klemens'  'Oli' ]
Ans = "" #@param ["A", "B", "C", "D"] {allow-input: true}

## **Pandas**

Pandas is a Python library used for working with data sets. It has functions for analyzing, cleaning, exploring, and manipulating data. The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

Pandas allows us to analyze big data and make conclusions based on statistical theories. Pandas can clean messy data sets, and make them readable and relevant.

The documentation of Pandas can be found [here.](https://pandas.pydata.org/pandas-docs/stable/index.html)

To use Pandas, we first need to install and import the `pandas` package:

In [ ]:
!pip install pandas

### **Data frames**

Pandas DataFrame is a two-dimensional data structure, like a two-dimensional array, or a table with rows and columns.

In [ ]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

**Locate Row:**

As you can see from the result above, the DataFrame is like a table with rows and columns. 

Pandas use the `loc` attribute to return one or more specified row(s)

In [ ]:
# return row 0
print(df.loc[0])

In [ ]:
# return row 0 and 1
print(df.loc[[0, 1]])

**Named Indexes:**

With the `index` argument, you can name your own indexes.

In [ ]:
# add a list of names to give each row a name
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df) 

**Locate Named Indexes**


Use the named `index` in the loc attribute to return the specified row(s).

In [ ]:
# refer to the named index
print(df.loc["day2"])

### **Data visualization**

**Read CSV Files:**

A simple way to store big data sets is to use CSV files (comma separated files). CSV files contains plain text and is a well know format that can be read by everyone including Pandas.

In [ ]:
import pandas as pd

# load the CSV into a DataFrame
df = pd.read_csv('https://www.w3schools.com/python/pandas/data.csv.txt')

print(df)

View the first 5 rows of the DataFrame:

In [ ]:
df.head()

In [ ]:
df.head(5)

View the first 20 rows of the DataFrame:

In [ ]:
df.head(20)

View the last 5 rows of the DataFrame:

In [ ]:
df.tail()

In [ ]:
df.tail(5)

View the last 20 rows of the DataFrame:

In [ ]:
df.tail(20)

**Information of the data:**

The DataFrames object has methods called `info()` and `describe()` that gives you more information about the data set.


In [ ]:
df.info()

In [ ]:
df.describe()

### **Data cleaning**

**Data cleaning fixing and removing bad data from the dataset and bad data could be:**

* Empty cells
* Data in wrong format
* Wrong data
* Duplicates 

In [ ]:
import pandas as pd

# load the CSV (with bad data) into a DataFrame
df = pd.read_csv('https://www.w3schools.com/python/pandas/dirtydata.csv.txt')

print(df)

**The data set contains:**

* Empty cells ("Date" in row 22, and "Calories" in row 18 and 28).

* Wrong format ("Date" in row 26).

* Wrong data ("Duration" in row 7).

* Duplicates (row 11 and 12).

#### **Empty cells**

**Remove Rows:**

One way to deal with empty cells is to remove rows that contain empty cells using `dropna()` method

This is usually OK, since data sets can be very big, and removing a few rows will not have a big impact on the result.

In [ ]:
import pandas as pd

df = pd.read_csv('https://www.w3schools.com/python/pandas/dirtydata.csv.txt')
new_df = df.dropna()          # remove rows that contain empty cells

print(new_df)

#### **Wrong format**

Cells with data of wrong format can make it difficult, or even impossible, to analyze data. 

To fix it, you have two options: remove those particular rows, or convert all cells in the columns into the same format.

In [ ]:
import pandas as pd

df = pd.read_csv('https://www.w3schools.com/python/pandas/dirtydata.csv.txt')
df['Date'] = pd.to_datetime(df['Date'])

print(df)

As you can see from the result, the date in row 26 was fixed, but the date in the row 22 got a NaT (Not a Time) value, in other words an empty value. One way to deal with empty values is simply removing the entire row using `dropna()` method

#### **Wrong data**

"Wrong data" does not have to be "empty cells" or "wrong format", it can just be wrong, like if someone registered "199" instead of "1.99". Sometimes you can spot wrong data by looking at the data set, because you have an expectation of what it should be.

If you take a look at the data set, you can see that in row 7, the duration is 450, but for all the other rows the duration is between 30 and 60. It doesn't have to be wrong, but taking in consideration that this is the data set of someone's workout sessions, we conclude with the fact that this person did not work out for 450 minutes.

In [ ]:
df.loc[7, 'Duration'] = 45
print(df.dropna())

#### **Duplicates**

Duplicate rows are rows that have been registered more than one time. By taking a look at our test data set, we can assume that row 11 and 12 are duplicates.

**Discovering duplicates:**
we can use the `duplicated()` method.

In [ ]:
print(df.duplicated())

**Removing duplicates:**
We can use the `drop_duplicates()` method.

In [ ]:
df.drop_duplicates(inplace = True)
print(df.dropna())

In [ ]:
#@title Questionnaire: 
#@markdown 9. What is a correct syntax to create a Pandas DataFrame?
#@markdown - A) pd.dataframe(data)
#@markdown - B) pd.df(data)
#@markdown - C) pd.DataFrame(data)
Ans = "" #@param ["A", "B", "C"] {allow-input: true}

In [ ]:
#@title Questionnaire: 
#@markdown 10. What is the correct Pandas function for loading CSV files into a DataFrame?
#@markdown - A) ReadFile()
#@markdown - B) read_file()
#@markdown - C) read_csv()
#@markdown - D) ReadCSV()
Ans = "" #@param ["A", "B", "C", "D"] {allow-input: true}

In [ ]:
#@title Questionnaire: 
#@markdown 11. When you print a DataFrame, by default you will get the headers and how many rows?
#@markdown - A) the first 10
#@markdown - B) the first 5 and the last 5
#@markdown - C) the first 5
#@markdown - D) the first 10 and the last 10
Ans = "" #@param ["A", "B", "C", "D"] {allow-input: true}

In [ ]:
#@title Questionnaire: 
#@markdown 12. What is a correct Pandas method for removing rows that contains empty cells?
#@markdown - A) dropna()
#@markdown - B) remove_null()
#@markdown - C) delete_null
Ans = "" #@param ["A", "B", "C"] {allow-input: true}

In [ ]:
#@title Questionnaire: 
#@markdown 13. What is a correct method to remove duplicates from a Pandas DataFrame?
#@markdown - A) df.delete_duplicates()
#@markdown - B) df.drop_duplicates()
#@markdown - C) df.remove_duplicates()
#@markdown - D) df.duplicates()
Ans = "" #@param ["A", "B", "C", "D"] {allow-input: true}

## **Matplotlib**

Matplotlib is a plotting library and this section gives a brief introduction to the `matplotlib.pyplot` module, which provides a plotting system similar to that of MATLAB.

To use Matplotlib, we first need to install and import the `matplotlib` package:

In [ ]:
!pip install matplotlib
import matplotlib.pyplot as plt     #Importing the package/dependencies

By running this special iPython command, we will be displaying plots inline:

In [ ]:
%matplotlib inline

### **Plotting**

The most important function in `matplotlib` is plot, which allows you to plot 2D data. Here is a simple example:

In [ ]:
# compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# plot the points using matplotlib
plt.plot(x, y)

With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])

### **Subplots**

You can plot different things in the same figure using the subplot function. Here is an example:

In [ ]:
# compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# show the figure.
plt.show()

You can read much more about the `subplot` function in the [documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot).

### **Images**

Matplotlib can display images (assuming equally spaced horizontal dimensions) using the `imshow()` function.

In [ ]:
import numpy as np
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import matplotlib.cbook as cbook
from matplotlib.path import Path
from matplotlib.patches import PathPatch


# fixing random state for reproducibility
np.random.seed(19680801)

delta = 0.025
x = y = np.arange(-3.0, 3.0, delta)
X, Y = np.meshgrid(x, y)
Z1 = np.exp(-X**2 - Y**2)
Z2 = np.exp(-(X - 1)**2 - (Y - 1)**2)
Z = (Z1 - Z2) * 2

fig, ax = plt.subplots()
im = ax.imshow(Z, interpolation='bilinear', cmap=cm.RdYlGn,
               origin='lower', extent=[-3, 3, -3, 3],
               vmax=abs(Z).max(), vmin=-abs(Z).max())

plt.show()

### **Contouring and Pseudocolor**

The `pcolormesh()` function can make a colored representation of a two-dimensional array, even if the horizontal dimensions are unevenly spaced. The `contour()` function is another way to represent the same data:

In [ ]:
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.colors import BoundaryNorm
from matplotlib.ticker import MaxNLocator
import numpy as np

np.random.seed(19680801)
Z = np.random.rand(6, 10)
x = np.arange(-0.5, 10, 1)  # len = 11
y = np.arange(4.5, 11, 1)  # len = 7

fig, ax = plt.subplots()
ax.pcolormesh(x, y, Z)

### **Histograms**

The `hist()` function automatically generates histograms and returns the bin counts or probabilities:

In [ ]:
import matplotlib
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(19680801)

# example data
mu = 100  # mean of distribution
sigma = 15  # standard deviation of distribution
x = mu + sigma * np.random.randn(437)

num_bins = 50

fig, ax = plt.subplots()

# the histogram of the data
n, bins, patches = ax.hist(x, num_bins, density=True)

# add a 'best fit' line
y = ((1 / (np.sqrt(2 * np.pi) * sigma)) *
     np.exp(-0.5 * (1 / sigma * (bins - mu))**2))
ax.plot(bins, y, '--')
ax.set_xlabel('Smarts')
ax.set_ylabel('Probability density')
ax.set_title(r'Histogram of IQ: $\mu=100$, $\sigma=15$')

# tweak spacing to prevent clipping of ylabel
fig.tight_layout()
plt.show()

### **Scatter plots**

The `scatter()` function makes a scatter plot with (optional) size and color arguments.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(19680801)
fig, ax = plt.subplots()
for color in ['tab:blue', 'tab:orange', 'tab:green']:
    n = 750
    x, y = np.random.rand(2, n)
    scale = 200.0 * np.random.rand(n)
    ax.scatter(x, y, c=color, s=scale, label=color,
               alpha=0.3, edgecolors='none')

ax.legend()
ax.grid(True)

plt.show()

In [ ]:
#@title Questionnaire: 
#@markdown 14. In what order should you run the following commands in order to generate and display a plot?
#@markdown  - *1. plt.legend()*
#@markdown  - *2. x = np.linspace(1, 10, 20)*
#@markdown  - *3. plt.show()*
#@markdown  - *4. plt.xlabel('X-Label')*
#@markdown  - *5. plt.plot(x, label='Example Plot')*

#@markdown - A) 4 - 2 - 1 - 3 - 5
#@markdown - B) 2 - 5 - 4 - 1 - 3
#@markdown - C) 5 - 4 - 1 - 3 - 2
#@markdown - D) 1 - 2 - 4 - 3 - 5

Ans = "" #@param ["A", "B", "C", "D"] {allow-input: true}